name: SENG3011 Performance AND Functionality Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs the test every 6 hours
    - cron: '0 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          
      - name: Install root dependencies
        run: npm install
        
      - name: Install TradeTuah API test dependencies
        run: npm install
        working-directory: tests/stock-tests
        
      - name: Install SIERRA Investments test dependencies
        run: npm install
        working-directory: tests/esg-tests
        
      - name: Install integration test dependencies
        run: npm install
        working-directory: tests/integration-tests
        
      - name: Run TradeTuah API performance tests
        run: npm test || echo "Tests failed but continuing workflow"
        working-directory: tests/stock-tests
        env:
          NODE_ENV: test
          
      - name: Run SIERRA Investments performance tests
        run: npm test || echo "Tests failed but continuing workflow"
        working-directory: tests/esg-tests
        env:
          NODE_ENV: test
          
      - name: Run integration tests
        run: npm test || echo "Tests failed but continuing workflow"
        working-directory: tests/integration-tests
        env:
          NODE_ENV: test
      
      - name: Create combined Markdown report
        run: |
          echo "# API Performance and Functionality Test Report" > combined-results.md
          echo "**Generated on:** $(date)" >> combined-results.md
          echo "" >> combined-results.md
          echo "## Test Environment" >> combined-results.md
          echo "- GitHub Actions Runner (Uses Ubuntu Latest)" >> combined-results.md
          echo "- Node.js v22.x" >> combined-results.md
          echo "" >> combined-results.md
          
          echo "## TradeTuah API Results" >> combined-results.md
          echo '```' >> combined-results.md
          if [ -f tests/stock-tests/test-results.txt ]; then
            cat tests/stock-tests/test-results.txt >> combined-results.md
          else
            echo "No results available - tests may have failed completely" >> combined-results.md
          fi
          echo '```' >> combined-results.md
          echo "" >> combined-results.md
          
          echo "## SIERRA Investments Results" >> combined-results.md
          echo '```' >> combined-results.md
          if [ -f tests/esg-tests/test-results.txt ]; then
            cat tests/esg-tests/test-results.txt >> combined-results.md
          else
            echo "No results available - tests may have failed completely" >> combined-results.md
          fi
          echo '```' >> combined-results.md
          echo "" >> combined-results.md
          
          echo "## Integration Test Results" >> combined-results.md
          echo '```' >> combined-results.md
          if [ -f tests/integration-tests/integration-results.txt ]; then
            cat tests/integration-tests/integration-results.txt >> combined-results.md
          else
            echo "No integration test results available" >> combined-results.md
          fi
          echo '```' >> combined-results.md
          echo "" >> combined-results.md
          
          echo "## Potential errors" >> combined-results.md
          echo "Some endpoints may experience errors at any point of testing:" >> combined-results.md
          echo "This is due to the API endpoint being modified or the API being down for any reason." >> combined-results.md
          echo "" >> combined-results.md
          echo "### TradeTuah API" >> combined-results.md
          echo "- **Historical data endpoint**: May return 500 error" >> combined-results.md
          echo "- **Earnings endpoint**: May return 500 error" >> combined-results.md
          echo "" >> combined-results.md
          echo "These errors are being handled through a catch block and do not indicate a problem with the testing framework itself." >> combined-results.md
          echo "These errors are could be due to the API endpoint being modified or the API being down for any reason." >> combined-results.md
          echo "" >> combined-results.md
          
          echo "## Functionality Testing" >> combined-results.md
          echo "The automated tests measure both performance and functionality:" >> combined-results.md
          echo "" >> combined-results.md
          
          echo "### TradeTuah API Functionality" >> combined-results.md
          echo "- **Overview endpoint**: Returns basic company information and summary" >> combined-results.md
          echo "- **Price endpoint**: Returns current and historical price data" >> combined-results.md
          echo "- **Options endpoint**: Returns options chain data" >> combined-results.md
          echo "- **Fundamentals endpoint**: Returns key financial metrics" >> combined-results.md
          echo "- **Historical data endpoint**: Returns detailed time-series data" >> combined-results.md
          echo "- **Earnings endpoint**: Returns quarterly earnings results" >> combined-results.md
          echo "" >> combined-results.md
          echo "Success criteria: Each endpoint returns HTTP 200 with valid JSON data structure" >> combined-results.md
          echo "" >> combined-results.md
          
          echo "### SIERRA Investments Functionality" >> combined-results.md
          echo "- **All ESG data endpoint**: Returns comprehensive dataset" >> combined-results.md
          echo "- **Company-specific ESG endpoint**: Returns ESG metrics for a specific ticker" >> combined-results.md
          echo "- **Score range search endpoint**: Returns companies within specified ESG score range" >> combined-results.md
          echo "- **ESG level search endpoint**: Returns companies with specified ESG grade" >> combined-results.md
          echo "- **Company name search endpoint**: Returns ESG data for companies matching search term" >> combined-results.md
          echo "" >> combined-results.md
          echo "Success criteria: Each endpoint returns HTTP 200 with correctly structured data" >> combined-results.md
          echo "" >> combined-results.md
          
          echo "## Integration Testing" >> combined-results.md
          echo "Integration tests ensures data is consistent between the TradeTuah and SIERRA Investments APIs:" >> combined-results.md
          echo "" >> combined-results.md
          echo "### Disney Ticker Consistency" >> combined-results.md
          echo "- Ensure that Disney (DIS) ticker is consistent across both TradeTuah and SIERRA Investments" >> combined-results.md
          echo "- Confirm both TradeTuah and Sierra Investments APIs identify the company as Disney" >> combined-results.md
          echo "" >> combined-results.md
          echo "### Companies in SIERRA Investments exists in TradeTuah" >> combined-results.md
          echo "- Tests if popular companies like Apple (AAPL), Microsoft (MSFT), and Google (GOOGL) exist in both APIs" >> combined-results.md
          echo "- Verify ticker is consistent between TradeTuah and Sierra Investments API" >> combined-results.md
          echo "" >> combined-results.md
          
          echo "## Performance Analysis" >> combined-results.md
          echo "- Response times above 1000ms may indicate performance issues, but this is expected due to the nature of the API." >> combined-results.md
          echo "- Historical responses typically take longer due to data volume" >> combined-results.md
          echo "- Search endpoints may vary based on query complexity or query fields" >> combined-results.md
          echo "- Endpoints are tested individually and concurrently to simulate a real-world scenario" >> combined-results.md
          echo "" >> combined-results.md

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install LaTeX dependencies
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra
        
      - name: Convert Markdown to PDF
        run: pandoc combined-results.md -o performance-report.pdf
          
      - name: Upload individual test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            tests/stock-tests/test-results.txt
            tests/esg-tests/test-results.txt
            tests/integration-tests/integration-results.txt
          retention-days: 30
          
      - name: Upload PDF report
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: performance-report.pdf
          retention-days: 30 