name: SENG3011 Performance Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
    
    - name: Run performance tests
      run: |
        cd tests/stock-tests
        npm test
      env:
        NODE_ENV: test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: performance-test-results
        path: tests/stock-tests/test-results.txt
        retention-days: 30 